kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: chaos-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: chaos-agent
  template:
    metadata:
      labels:
        app: chaos-agent
    spec:
      containers:
      - name: chaos-agent
        image: kirill02102/chimp-chaos-agent
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-agent
  namespace: default
spec:
  selector:
    app: chaos-agent
  ports:
  - name: http
    port: 50051
    targetPort: 50051
  type: ClusterIP
