kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: chaos-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: chaos-agent
  template:
    metadata:
      labels:
        app: chaos-agent
    spec:
      containers:
      - name: chaos-agent
        image: chaos-agent:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          sleep 30
          echo "Chaos agent started"
